import type { Page } from '../../interfaces/index';

const FAQ: Page = () => {
  return (
    <div>
      <h2>FAQ</h2>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
      <p>content</p><br/>
    </div>
  );
};
FAQ.title = 'Frequently Asked Questions';

export default FAQ;
